<?php
/** @var $block Rovexo\Configbox\Block\Product\View\Options\Type\ConfigboxConfigurator */
/** @var $this Rovexo\Configbox\Block\Product\View\Options\Type\ConfigboxConfigurator */
$optionId = (int) $block->getOption()->getId();

/**
 * The hidden text field below accommodates two things:
 * - validation on 'add to cart' (see initMagento2Validation in JS module configbox/m2)
 * - Somehow needed for M2's total price init (to be confirmed)
 */
?>

<input type="text"
       style="display:block;border:none;width:0;height:0;position:absolute;left:-3000px;"
       id="options_<?php echo (int) $optionId; ?>_text"
       name="options[<?php echo (int) $optionId;?>]"
       class="input-text product-custom-option"
       data-selector="options[<?php echo (int) $optionId; ?>]"
       data-validate="{configbox_m2_validation: true}"
       value="dummy value" />

<?php
KenedoView::getView('ConfigboxViewM2configurator')
    ->setConfigInfo($block->getConfigInfo())
    ->setTaxRate($block->getTaxRate())
    ->setMagentoOptionId($optionId)
    ->display();

